/* ==========================================================================
   Portfolio project data
   Source of truth: "Projects Master.xlsx" (Project Name, Project Team,
   Clients, Year, Tags, Web Link, Project Summary, Leading Image name,
   Other image 1, Other image 2). Titles, links, and images below all come
   directly from that workbook -- images referenced here are expected to
   live in images/portfolio_2026/ alongside these HTML files.

   HOW TO EDIT / ADD PROJECTS
   Each object below is one portfolio card.
   - images: an array of image paths (relative to the site root). The first
     one is used as the card thumbnail. Add more paths to the array to turn
     the project's detail view into a swipeable gallery -- no other code
     changes needed. Use an empty array [] to show a plain document
     placeholder until a graphic is ready.
   - link: { label, url } or null if there's nothing to link to yet
   - skills: pick from SKILL_OPTIONS where possible so the skill filter
     stays consistent
   - sortYear: a plain number used only for the "Sort by Year" control --
     for projects spanning multiple years this is the most recent one
   ========================================================================== */

const SKILL_OPTIONS = [
  "Illustrator",
  "Photoshop",
  "InDesign",
  "AutoCAD",
  "SketchUp",
  "Lumion",
  "ArcGIS",
  "Research & Writing",
];

// Fixed display order for the "Filter by project team" chips (career
// chronology / relevance, rather than alphabetical). Any team name not
// listed here -- e.g. a new one you start using -- will simply appear after
// these, sorted alphabetically, so nothing breaks if you add one.
const TEAM_ORDER = [
  "NUE Urban Concepts",
  "Urbe Studio",
  "Kittelson",
  "City of Oakland",
  "City of Gainesville",
  "Student",
  "Independent Project",
];

const PROJECTS = [
  {
    id: "city-of-palm-beach-gardens-citywide-mobility-plan",
    title: "City of Palm Beach Gardens Citywide Mobility Plan & Mobility Fee",
    description: "I designed the Mobility Plan document as a whole and created more than 15 renderings for proposed improvements such as elevated walkways, separated bike lanes, and new shared-use paths throughout the city.",
    year: "2025",
    sortYear: 2025,
    team: "NUE Urban Concepts",
    client: "City of Palm Beach Gardens",
    skills: ["Photoshop", "Illustrator", "InDesign", "SketchUp"],
    images: ["images/portfolio_2026/Palm_Beach_Gardens.jpg"],
    link: { label: "Project Website", url: "https://www.pbgfl.gov/860/Mobility" },
  },
  {
    id: "hialeah-2050-master-plan-w-29th-street-redesign-al",
    title: "Hialeah 2050 Master Plan - W 29th Street Redesign Alternatives",
    description: "I developed a street redesign for 2 miles of W 29th Street as part of Hialeah 2050 Master Plan. The proposed road diet adds shared-use paths on both sides of the street, new midblock crossings, roundabouts, and raised intersections.",
    year: "2025",
    sortYear: 2025,
    team: "Urbe Studio",
    client: "City of Hialeah",
    skills: ["SketchUp", "AutoCAD"],
    images: ["images/portfolio_2026/W29th_Street.jpg", "images/portfolio_2026/W29th_Street_1.jpg"],
    link: { label: "Project Website", url: "https://www.hialeah2050.com/" },
  },
  {
    id: "hialeah-2050-master-plan-safe-access-to-schools-pa",
    title: "Hialeah 2050 Master Plan - Safe Access to Schools & Parks Maps",
    description: "I developed maps for 3 schools and parks as part of Hialeah 2050 Master Plan. Our team at Urbe Studio developed infrastructure recommendations to enhance the safe access to parks and schools for walking kids and their families.",
    year: "2025",
    sortYear: 2025,
    team: "Urbe Studio",
    client: "City of Hialeah",
    skills: ["ArcGIS", "Illustrator", "InDesign"],
    images: ["images/portfolio_2026/Hialeah_Maps.jpg"],
    link: { label: "Project Website", url: "https://www.hialeah2050.com/" },
  },
  {
    id: "broward-safety-action-plan-access-to-schools-maps",
    title: "Broward Safety Action Plan - Access to Schools Maps",
    description: "I developed maps for 3 school zones as part of the School Zones & Bus Stop Safety Action Plan within the Broward SS4A project. The Urbe Studio team developed infrastructure recommendations to enhance the safe access to schools for walking kids and their families.",
    year: "2025",
    sortYear: 2025,
    team: "Urbe Studio",
    client: "Broward MPO",
    skills: ["ArcGIS", "Illustrator", "InDesign"],
    images: ["images/portfolio_2026/Broward_SS4A_Maps.jpg"],
    link: { label: "Project Website", url: "https://broward-safety-action-plan-browardmpo.hub.arcgis.com/pages/the-action-plan" },
  },
  {
    id: "broward-safety-action-plan-quick-build-renderings",
    title: "Broward Safety Action Plan - Quick-Build Renderings",
    description: "I developed renderings for 3 of the 10 quick-build concepts that we developed as part of the Broward County Safety Action Plan (SS4A). These renderings were included with the quick-build concept designs to aid with stakeholder engagement prior to implementation.",
    year: "2025",
    sortYear: 2025,
    team: "Urbe Studio",
    client: "Broward MPO",
    skills: ["AutoCAD", "SketchUp", "Lumion", "Illustrator", "Photoshop"],
    images: ["images/portfolio_2026/Broward_SS4A_1.jpg", "images/portfolio_2026/Broward_SS4A_2.jpg", "images/portfolio_2026/Broward_SS4A_3.jpg"],
    link: { label: "Project Website", url: "https://broward-safety-action-plan-browardmpo.hub.arcgis.com/pages/the-action-plan" },
  },
  {
    id: "broward-safety-action-plan-quick-build-concepts",
    title: "Broward Safety Action Plan - Quick-Build Concepts",
    description: "I developed quick-build concept plans for 10 corridors in 10 different cities within Broward County. These quick-build concepts were developed as part of Broward County Safety Action Plan (SS4A). These 10 concept plans were designed along high-impact corridors as examples for different jurisdictions to use as needed to address traffic safety issues. Safety countermeasures in these designs included mini traffic circles, curb extensions, high-visibility crossings, lane repurposings, protected bike lanes, new on-street parking, and one-way conversions, among others.",
    year: "2025",
    sortYear: 2025,
    team: "Urbe Studio",
    client: "Broward MPO",
    skills: ["ArcGIS", "AutoCAD", "Illustrator", "Photoshop", "InDesign"],
    images: ["images/portfolio_2026/Broward_SS4A.jpg"],
    link: { label: "Project Website", url: "https://broward-safety-action-plan-browardmpo.hub.arcgis.com/pages/the-action-plan" },
  },
  {
    id: "city-of-gainesville-2045-mobility-plan-mobility-fe",
    title: "City of Gainesville 2045 Mobility Plan & Mobility Fee",
    description: "I designed the Mobility Plan document, in which I added drone photos taken by me. I coordinated with the graphics and mapping team to collect all necessary text and images to include as part of the report.",
    year: "2024",
    sortYear: 2024,
    team: "NUE Urban Concepts",
    client: "City of Gainesville",
    skills: ["Illustrator", "InDesign"],
    images: ["images/portfolio_2026/Gainesville.jpg"],
    link: { label: "Project Website", url: "https://www.gainesvillefl.gov/Government-Pages/Government/Departments/Transportation/Mobility-Plan" },
  },
  {
    id: "west-colonial-drive-corridor-study-creative-placem",
    title: "West Colonial Drive Corridor Study & Creative Placemaking",
    description: "I developed renderings, maps, and a placemaking toolbox to aid in the development of a creative placemaking strategy for West Colonial Drive in Orlando, FL to activate two public spaces and foster community engagement.",
    year: "2024",
    sortYear: 2024,
    team: "Urbe Studio",
    client: "City of Orlando",
    skills: ["SketchUp", "Illustrator", "Photoshop", "InDesign"],
    images: ["images/portfolio_2026/Colonial.jpg"],
    link: { label: "Project Website", url: "https://www.orlando.gov/Our-Government/Departments-Offices/Economic-Development/City-Planning/Plans-Studies/West-Colonial-Drive-Corridor-Study" },
  },
  {
    id: "south-miami-placemaking-branding-urban-design-exis",
    title: "South Miami Placemaking, Branding & Urban Design - Existing Conditions Evaluation",
    description: "I developed a series of 50 maps to inform the existing conditions analysis for the Study Area. Maps included zoning and land use, urban heat island, tree canopy, bicycle infrastructure, and the development of a pedestrian comfort analysis, among others.",
    year: "2024",
    sortYear: 2024,
    team: "Urbe Studio",
    client: "City of South Miami",
    skills: ["ArcGIS", "Illustrator"],
    images: ["images/portfolio_2026/South_Miami_Placemaking.jpg"],
    link: { label: "Project Website", url: "https://southmiamifl.gov/DocumentCenter/View/7890/2-Transportation-and-Travel-Mode-Characteristics?bidId=" },
  },
  {
    id: "south-miami-placemaking-branding-urban-design-mult",
    title: "South Miami Placemaking, Branding & Urban Design - Multimodal Recommendations",
    description: "I helped develop a Multimodal Recommendations plan with 19 one-page summaries and associated maps for each proposed multimodal recommendation, and summary project tables. These recommendations will improve safety, accessibility, and mobility by adding bicycle and pedestrian infrastructure such as bike lanes, curb ramps, high-visibility crossings, LPIs, curb extensions, and intersection reconfigurations, among other measures.",
    year: "2024",
    sortYear: 2024,
    team: "Urbe Studio",
    client: "City of South Miami",
    skills: ["ArcGIS", "Illustrator", "InDesign"],
    images: ["images/portfolio_2026/South_Miami_Multimodal.jpg"],
    link: { label: "Project Website", url: "https://southmiamifl.gov/DocumentCenter/View/7868/08-15-2024-South-Miami-Placemaking---Urban-Design-Services---Multimodal-Plan?bidId=" },
  },
  {
    id: "south-miami-placemaking-branding-urban-design-sw-7",
    title: "South Miami Placemaking, Branding & Urban Design - SW 73rd Street Redesign Alternatives",
    description: "I developed street redesign alternatives for SW 73rd Street as part of South Miami’s Hometown District Placemaking, Branding & Urban Design project. The two proposed design options include a curbless shared street with sharrows or a separated two-way cycle track. I developed concept plan drawings and accompanying 3D renderings.",
    year: "2024",
    sortYear: 2024,
    team: "Urbe Studio",
    client: "City of South Miami",
    skills: ["AutoCAD", "SketchUp"],
    images: ["images/portfolio_2026/SW73rd_Street_Plan.jpg", "images/portfolio_2026/SW73rd_Street.jpg"],
    link: null,
  },
  {
    id: "city-of-north-miami-2045-mobility-action-plan",
    title: "City of North Miami 2045 Mobility Action Plan",
    description: "I designed the Mobility Action Plan document and a series of 8 one-pagers that explain the different types of street treatments and pilot programs proposed as part of the Plan.",
    year: "2024",
    sortYear: 2024,
    team: "NUE Urban Concepts",
    client: "City of North Miami",
    skills: ["ArcGIS", "AutoCAD", "Illustrator", "InDesign"],
    images: ["images/portfolio_2026/North_Miami.jpg"],
    link: { label: "Project Website", url: "https://www.northmiamifl.gov/DocumentCenter/View/19150/North-Miami-2045-Mobility-Action-Plan-PDF" },
  },
  {
    id: "blue-zones-upper-napa-valley-wayfinding",
    title: "Blue Zones - Upper Napa Valley Wayfinding",
    description: "I designed and developed pedestrian wayfinding signs for the cities of St. Helena and Yountville in Napa Valley, California. These wayfinding signs are meant to guide elderly pedestrians through curated walking routes to enhance their health and well-being.",
    year: "2023–2024",
    sortYear: 2024,
    team: "Urbe Studio",
    client: "Blue Zones",
    skills: ["Illustrator"],
    images: ["images/portfolio_2026/Blue_Zones.jpg"],
    link: { label: "Project Website", url: "https://www.bluezones.com/" },
  },
  {
    id: "blue-zones-ignite-basemaps",
    title: "Blue Zones Ignite - Basemaps",
    description: "I created basemaps for BlueZones Ignite projects in San Mateo, San Marcos and Rio Grande Valley in California, and Riverside and Tyler in Texas.",
    year: "2025",
    sortYear: 2025,
    team: "Urbe Studio",
    client: "Blue Zones Ignite",
    skills: ["ArcGIS", "Illustrator"],
    images: ["images/portfolio_2026/Blue_Zones_Maps.jpg"],
    link: { label: "Project Website", url: "https://www.bluezones.com/" },
  },
  {
    id: "city-of-orlando-project-dto-2-0-action-plan-roadwa",
    title: "City of Orlando Project DTO 2.0 Action Plan - Roadway Reconfiguration Concepts",
    description: "I developed street redesigns for more than 30 city blocks within Downtown Orlando to show future conditions where streets are converted to two-way. Some corridors also included the addition of two-way separated cycle tracks, on-street parking, and pedestrian improvements.",
    year: "2023",
    sortYear: 2023,
    team: "Urbe Studio",
    client: "City of Orlando",
    skills: ["AutoCAD"],
    images: ["images/portfolio_2026/Orlando_DTO.jpg"],
    link: { label: "Project Website", url: "https://www.downtownorlando.com/About/DTO-Action-Plan" },
  },
  {
    id: "polk-city-vision-action-plan-intersection-concept",
    title: "Polk City Vision & Action Plan - Intersection Concept Rendering",
    description: "I developed 3D renderings to accompany the Vision Plan and show proposed alternatives for intersection improvements.",
    year: "2023",
    sortYear: 2023,
    team: "Urbe Studio",
    client: "City of Polk City, Florida Department of Transportation",
    skills: ["AutoCAD", "SketchUp", "Photoshop", "Illustrator"],
    images: ["images/portfolio_2026/Polk.jpg"],
    link: { label: "Project Website", url: "https://www.mypolkcity.org/" },
  },
  {
    id: "vdot-bicycle-pedestrian-treatments",
    title: "VDOT Bicycle & Pedestrian Treatments",
    description: "I created a collection of 3D visualizations to aid the Virginia Department of Transportation with the creation of an online guide for bicycle and pedestrian treatments that enhance safety and mobility for all road users.",
    year: "2021",
    sortYear: 2021,
    team: "Kittelson",
    client: "Virginia Department of Transportation",
    skills: ["AutoCAD", "SketchUp", "Lumion"],
    images: ["images/portfolio_2026/VDOT_Treatments.jpg"],
    link: { label: "Project Website", url: "https://www.vdot.virginia.gov/doing-business/technical-guidance-and-support/transportation-and-mobility-planning/bicycle-and-pedestrian-accommodations/bicycle-and-pedestrian-treatments/" },
  },
  {
    id: "cheltenham-drive-bikeway-feasibility-study",
    title: "Cheltenham Drive Bikeway Feasibility Study",
    description: "I created existing and proposed typical cross-sections for 9 road segements in Bethesda. I also created 5 before-and-after renders to show proposed alternatives for a bikeway along Cheltenham Drive.",
    year: "2021",
    sortYear: 2021,
    team: "Kittelson",
    client: "Montgomery County Department of Transportation",
    skills: ["SketchUp", "Lumion"],
    images: ["images/portfolio_2026/Cheltenham_Drive.jpg"],
    link: { label: "Read the Report", url: "https://assets.montgomerycountymd.gov/files/dot-dte/resources/files/cheltenhamdr/Cheltenham%20Public%20Meeting_2021_09_28.pdf" },
  },
  {
    id: "pittsfield-bicycle-facilities-master-plan",
    title: "Pittsfield Bicycle Facilities Master Plan",
    description: "I created the graphics for the Design Guidelines chapter of the Bicycle Facilities Master Plan to show minimum and recommended dimensions for bicycle infrastructure treatments such as separated bike lanes and neighborhood bike routes.",
    year: "2021",
    sortYear: 2021,
    team: "Kittelson",
    client: "City of Pittsfield",
    skills: ["AutoCAD", "SketchUp", "Lumion", "Illustrator", "Photoshop"],
    images: ["images/portfolio_2026/Pittsfield.jpg"],
    link: { label: "Read the Report", url: "https://bloximages.newyork1.vip.townnews.com/berkshireeagle.com/content/tncms/assets/v3/editorial/f/94/f94e0b70-e726-11eb-8eda-a3194f8edeec/60f3196087650.pdf.pdf" },
  },
  {
    id: "langley-park-neighborhood-bicycle-boulevards",
    title: "Langley Park Neighborhood Bicycle Boulevards",
    description: "I developed maps and 3D renderings to show existing and alternative future conditions for the area surrounding a future Purple Line station in Prince George’s County, Maryland. I also assisted with data analysis and report drafting.",
    year: "2021",
    sortYear: 2021,
    team: "Kittelson",
    client: "Price George's County Parks & Recreation",
    skills: ["AutoCAD", "SketchUp", "Illustrator"],
    images: ["images/portfolio_2026/LangleyPark.jpg"],
    link: { label: "Project Website", url: "https://issuu.com/mncppc/docs/langleyparkbikeboulevards" },
  },
  {
    id: "city-of-boston-neighborhood-slow-streets-quick-bui",
    title: "City of Boston Neighborhood Slow Streets Quick-Build",
    description: "I developed final construction documents for the installation of quick-build traffic calming treatments in the City of Boston. I also developed budget estimates for installation. I designed more than 20 intersection improvements.",
    year: "2021",
    sortYear: 2021,
    team: "Kittelson",
    client: "City of Boston",
    skills: ["AutoCAD"],
    images: ["images/portfolio_2026/Boston.jpg"],
    link: null,
  },
  {
    id: "nyc-citibike-station-placement-design",
    title: "NYC CitiBike Station Placement & Design",
    description: "I developed final construction drawings for the expansion of New York City’s bikeshare system. I have designed more than 75 stations throughout the five boroughs.",
    year: "2020–2021",
    sortYear: 2021,
    team: "Kittelson",
    client: "New York City",
    skills: ["AutoCAD"],
    images: ["images/portfolio_2026/CitiBike.jpg"],
    link: null,
  },
  {
    id: "shreve-road-corridor-study",
    title: "Shreve Road Corridor Study",
    description: "I developed 2D and 3D concept plans for proposed intersection modifications along the study corridor to help visualize solutions that would increase community buy-in. I also assisted with data analysis and report drafting.",
    year: "2020",
    sortYear: 2020,
    team: "Kittelson",
    client: "Virginia Department of Transportation",
    skills: ["AutoCAD", "SketchUp", "Photoshop"],
    images: ["images/portfolio_2026/Shreve.jpg"],
    link: { label: "Read the Report", url: "files/Shreve_Road_Corridor_Study.pdf" },
  },
  {
    id: "city-of-charlotte-uptown-cycle-link",
    title: "City of Charlotte Uptown Cycle Link",
    description: "I developed a series of 3D photorealistic renderings of proposed conditions to get community buy-in for a project that aimed to install approximately 7 miles of two-way cycle tracks in Downtown Charlotte, North Carolina.",
    year: "2020",
    sortYear: 2020,
    team: "Kittelson",
    client: "City of Charlotte",
    skills: ["AutoCAD", "SketchUp", "Photoshop", "Illustrator"],
    images: ["images/portfolio_2026/Uptown_Cycle_Link.jpg"],
    link: { label: "Project Website", url: "https://www.charlottenc.gov/Growth-and-Development/Projects/Uptown-CycleLink" },
  },
  {
    id: "fdot-bicycle-pedestrian-treatments",
    title: "FDOT Bicycle & Pedestrian Treatments",
    description: "I developed a series of 3D models depicting bicycle and pedestrian treatments at alternative intersections for Florida Department of Transportation. These 3D models were used as a base for video simulations showing movements within the system.",
    year: "2020",
    sortYear: 2020,
    team: "Kittelson",
    client: "Florida Department of Transportation",
    skills: ["AutoCAD", "SketchUp"],
    images: ["images/portfolio_2026/FDOT_Treatments.jpg"],
    link: { label: "Watch Video", url: "https://www.youtube.com/watch?v=FuraXfZxoE0" },
  },
  {
    id: "bicycle-pedestrian-wayfinding-maps",
    title: "Bicycle & Pedestrian Wayfinding Maps",
    description: "I designed bicycle and pedestrian wayfinding maps for the University of Florida as part of an independent initiative while I was the President of Students for New Urbanism at UF. These maps were posted on campus, and shared on social media and in a blog post.",
    year: "2019",
    sortYear: 2019,
    team: "Independent Project",
    client: "",
    skills: ["Illustrator"],
    images: ["images/portfolio_2026/Student_Engagement.jpg"],
    link: { label: "Read the Blog Post", url: "https://medium.com/@mateovtn/a-metro-style-pedestrian-map-for-uf-3c259d3adbf3" },
  },
  {
    id: "kermit-sigmon-bike-trail-alternatives",
    title: "Kermit Sigmon Bike Trail Alternatives",
    description: "I designed a collection of graphics to show an existing gap in the trail system that runs along Archer Rd in Gainesville, FL and a proposed solution to the problem.",
    year: "2019",
    sortYear: 2019,
    team: "Independent Project",
    client: "",
    skills: ["Illustrator", "Photoshop"],
    images: ["images/portfolio_2026/Kermit_Sigmon.jpg"],
    link: null,
  },
  {
    id: "ford-gobike-bikeshare-system-analysis",
    title: "Ford GoBike Bikeshare System Analysis",
    description: "I analyzed the use of Ford GoBike in Oakland, California, during its first year of use. This bikeshare analysis helped us understand equity and access issues as well as the system’s connectivity to the BART transit system. The results were shared through a blog post.",
    year: "2018",
    sortYear: 2018,
    team: "City of Oakland",
    client: "",
    skills: ["ArcGIS"],
    images: ["images/portfolio_2026/Ford_GoBike_Analysis.jpg"],
    link: { label: "Read the Blog Post", url: "https://medium.com/oakdot/after-one-year-of-ford-gobike-in-oakland-how-is-it-going-168e105368e3" },
  },
  {
    id: "ford-gobike-community-engagement",
    title: "Ford GoBike Community Engagement",
    description: "I created a series of visualizations and flyers to engage the community with a problematic bikeshare station in Fruitvale. The City of Oakland was going through its Bike Plan update and these efforts became part of the plan’s engagement activities.",
    year: "2018",
    sortYear: 2018,
    team: "City of Oakland",
    client: "",
    skills: ["AutoCAD", "Photoshop", "Illustrator"],
    images: ["images/portfolio_2026/Ford_GoBike_Engagement.jpg"],
    link: null,
  },
  {
    id: "a-geodesign-approach-to-understanding-urban-form-r",
    title: "A Geodesign Approach to Understanding Urban Form Resiliency in the State of Florida",
    description: "Undergraduate Honors Thesis exploring how geodesign methods can help evaluate the resiliency of urban form across the State of Florida.",
    year: "2019",
    sortYear: 2019,
    team: "Student",
    client: "",
    skills: ["ArcGIS", "Research & Writing"],
    images: ["images/portfolio_2026/Thesis.jpg"],
    link: { label: "Read the Thesis", url: "files/VanThienen_Mateo_2019_A_Geodesign_Approach_to_Better_Understand_the_Resiliency_of_Florida_Urban_Form.pdf" },
  },
  {
    id: "analyzing-gainesville-s-bicycle-infrastructure",
    title: "Analyzing Gainesville's Bicycle Infrastructure",
    description: "Intro to GIS research paper analyzing bicycle infrastructure coverage and gaps across Gainesville, FL.",
    year: "2018",
    sortYear: 2018,
    team: "Student",
    client: "",
    skills: ["ArcGIS", "Research & Writing"],
    images: ["images/portfolio_2026/DCP_2002.jpg"],
    link: { label: "Read the Paper", url: "files/DCP_2002_Final.pdf" },
  },
  {
    id: "new-archer-road-for-everyone",
    title: "New Archer Road for Everyone",
    description: "Personal project exploring a bus rapid transit (BRT) alignment along Archer Road in Gainesville, FL.",
    year: "2019",
    sortYear: 2019,
    team: "Independent Project",
    client: "",
    skills: ["Illustrator", "Photoshop"],
    images: ["images/portfolio_2026/Archer_Rd.jpg"],
    link: { label: "Read the Proposal", url: "files/NewArcherRd.pdf" },
  },
  {
    id: "weston-multimodal-plan-proposal",
    title: "Weston Multimodal Plan Proposal",
    description: "A proposal for the development of a Multimodal Plan for the City of Weston, FL.",
    year: "2025",
    sortYear: 2025,
    team: "Urbe Studio",
    client: "City of Weston",
    skills: ["ArcGIS", "SketchUp", "Photoshop", "Illustrator", "InDesign"],
    images: ["images/portfolio_2026/Weston_1.jpg", "images/portfolio_2026/Weston_2.jpg", "images/portfolio_2026/Weston_4.jpg"],
    link: { label: "Read the Proposal", url: "files/Weston_Multimodal_Plan_Proposal.pdf" },
  },
  {
    id: "city-of-cape-coral-2045-mobility-plan-mobility-fee",
    title: "City of Cape Coral 2045 Mobility Plan & Mobility Fee",
    description: "I designed the Mobility Plan document and prepared all maps and visualizations.",
    year: "2025",
    sortYear: 2025,
    team: "NUE Urban Concepts",
    client: "City of Cape Coral",
    skills: ["ArcGIS", "Illustrator", "Photoshop", "InDesign"],
    images: ["images/portfolio_2026/Cape_Coral_1.jpg"],
    link: { label: "Read the Report", url: "https://www.capecoral.gov/Documents/Departments/Public%20Works/Transportation%20Division/Cape%20Coral%20Mobility%20Plan.pdf?t=202605191321190" },
  },
  {
    id: "city-of-flagler-beach-2045-mobility-plan-mobility",
    title: "City of Flagler Beach 2045 Mobility Plan & Mobility Fee",
    description: "I designed the Mobility Plan document and prepared 3 renderings of proposed improvements.",
    year: "2026",
    sortYear: 2026,
    team: "NUE Urban Concepts",
    client: "City of Flagler Beach",
    skills: ["ArcGIS", "AutoCAD", "Photoshop", "Illustrator", "InDesign"],
    images: ["images/portfolio_2026/Flagler_Beach_1.jpg"],
    link: null,
  },
  {
    id: "city-of-lake-city-2050-mobility-plan-mobility-fee",
    title: "City of Lake City 2050 Mobility Plan & Mobility Fee",
    description: "I designed the Mobility Plan document, prepared maps, and designed one-page summaries for each mobility plan project type and other graphic elements in the plan.",
    year: "2026",
    sortYear: 2026,
    team: "NUE Urban Concepts",
    client: "City of Lake City",
    skills: ["ArcGIS", "Illustrator", "InDesign"],
    images: ["images/portfolio_2026/Lake_City_1.jpg", "images/portfolio_2026/Lake_City_2.jpg"],
    link: null,
  },
  {
    id: "city-of-port-st-lucie-2045-mobility-plan-mobility",
    title: "City of Port St Lucie 2045 Mobility Plan & Mobility Fee",
    description: "I designed the Mobility Plan document, prepared PDF maps and an online mapping application, and designed graphic elements in the mobility plan, such as the Multimodal Quality of Service graphics.",
    year: "2025",
    sortYear: 2025,
    team: "NUE Urban Concepts",
    client: "City of Port St Lucie",
    skills: ["ArcGIS", "InDesign", "Illustrator"],
    images: ["images/portfolio_2026/Port_St_Lucie_1.jpg", "images/portfolio_2026/Port_St_Lucie_2.jpg", "images/portfolio_2026/Port_St_Lucie_3.jpg"],
    link: { label: "Project Website", url: "https://www.cityofpsl.com/Government/Your-City-Government/Departments/Planning-Zoning/Mobility-Plan" },
  },
  {
    id: "city-of-west-palm-beach-2050-mobility-plan-mobilit",
    title: "City of West Palm Beach 2050 Mobility Plan & Mobility Fee",
    description: "I designed the Mobility Plan document, and prepared maps and other graphics.",
    year: "2026",
    sortYear: 2026,
    team: "NUE Urban Concepts",
    client: "City of West Palm Beach",
    skills: ["ArcGIS", "InDesign", "Illustrator", "Photoshop"],
    images: ["images/portfolio_2026/West_Palm_Beach.jpg"],
    link: { label: "Project Website", url: "https://www.wpb.org/Departments/Development-Services/City-of-West-Palm-Beach-Mobility-Fee" },
  },
  {
    id: "complete-streets-academy-quick-build-designs",
    title: "Complete Streets Academy Quick-Build Designs",
    description: "I developed a series of quick-build designs for 3 spot locations in Kentucky as part of Smart Growth America's Complete Streets Leadership Academy. The quick-build designs were informed by a walk audit and conversations with city leadership. Safety measures included protected bike lanes, protected intersections and bulb-outs, advisory sidewalks, and high-visibility crossings with curb extensions and street murals.",
    year: "2025",
    sortYear: 2025,
    team: "Urbe Studio",
    client: "Smart Growth America",
    skills: ["AutoCAD", "ArcGIS"],
    images: ["images/portfolio_2026/SGA.jpg"],
    link: { label: "Project Website", url: "https://www.smartgrowthamerica.org/knowledge-hub/resources/kentucky-complete-streets-leadership-academy/" },
  },
  {
    id: "lancaster-pa-quick-build-concepts",
    title: "Lancaster, PA - Quick-Build Concepts",
    description: "I designed 2 quick-build concepts for two different corridors in the City of Lancaster, PA to add multimodal safety elements, such as curb extensions and separated bike lanes. As part of this effort, I developed 2 renderings to use for stakeholder engagement prior to implementation.",
    year: "2021",
    sortYear: 2021,
    team: "Kittelson",
    client: "City of Lancaster",
    skills: ["AutoCAD", "SketchUp", "Lumion"],
    images: ["images/portfolio_2026/Lancaster_QuickBuild.jpg"],
    link: null,
  },
];
